project:
  type: book

jupyter: ds-6400

execute:
  freeze: auto
  warning: false

book:
  title: "DS 6400 Weekly Writing"
  author: "Wan Dang"
  date: "2026-08-27"
  cover-image: cover.png
  chapters:
    - index.qmd
    - part: "Weekly Writing"
      chapters:
        - weeks/01.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    code-fold: true
    code-summary: "Show code"
  pdf:
    documentclass: scrreprt
